require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.3

AllCops:
  Exclude:
    - vendor/**/*

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Metrics/AbcSize:
  Exclude:
    - spec/**/*

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/LineLength:
  Exclude:
    - lib/rubocop/cop/cask/homepage_matches_url.rb

Naming/FileName:
  Exclude:
    - lib/rubocop-cask.rb

Style/BlockDelimiters:
  EnforcedStyle: semantic

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

Style/SymbolArray:
  EnforcedStyle: brackets
