language: ruby

sudo: false

cache: bundler

rvm:
  - 2.3.3
  - 2.3.6
  - 2.4.3
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true

before_script:
  - git config --local user.email "travis@travis.ci"
  - git config --local user.name "Travis CI"
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - bundle exec rake coverage
  - bundle exec overcommit --sign
  - bundle exec overcommit --run

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

env:
  global:
    secure: gVhx28ayjkU9pMHUHvAx1M5onf7lES1wWTEIS8Mnkj0T2+c9Lx3Q3T/3oIKY99OamVSqfrIICc3rLTzk978KmlGoByzckWjXBZ2nE4k4kvD27hYXDTadMhLfVvultsVXwfJe07G+KOIbXI0xjaXueVPU9/daI7d0G5YdCElAXdBGgn0Z+8SqEY95Cd7/PdTVOeFtTXIRcfJH3HMOO+NMLI3fdA2VfXjYDmBnROS6oB6L3GI8YV5B+YeYreEXAyjt3oNz0ZHb4x5L+aMSlL1pkCQRs3Ot41MyczRjV+60inCWpqAs6iRbVP3+1Xr+zC55ezEcEGtX7YSMWY8/RVQT3I80YYl3KmSesEWhIiFYhTT+Zk67K7ZfBbnw+bWbH9uz981pHYIOhsVuQbMBHpK5ImC5Z0sbNe7RM1gzZzJaFh8k/teyL5awQASKsS18yP4JLRzzKajm+wHFY0BULK5xqftKn+f1gCwps8VX89jQ8v9te2tElzMGiaUciu6SLNABGuqLVwIOfhPgR60YftbYepcuZPebaEw79dsCn8f4VH9Cvloi78MAKOyhRf2+CEKT7wJbAXGYz4RGjyzgrS2+vkQp4B2dAgqWg7UqEy9HW5Uum127xyELYkhVg6KtmS4NGOKIm+46vzShnlMXD7QL+ZJ5tten+vUM9Mrg/wHzyFc=

deploy:
  provider: rubygems
  api_key:
    secure: brjKAkvncwFzlEzsURWIVp1JE9urVd2suzOUapMU8h1IkTkHTM4AHl/CDpNFMQNohLQFxIKivtpJsCsHJQS6WUhAazn4xRFgBmQ5Gv7S00vBvW2DbzTXnsGi+D5WGjfDdPPsbNOhxA58sT801yEu5r8Dt8Ywysqut6S3RJ2tZ9DvBtNluQde3CUZsCaiySGJmlbgcfdA0dKk4HI0P4BssPLYa6FX+oclTl1zkjRXaTA2UaltCUlCqWsyOwZxUOKK0U5apySYbCa9wjXKMqSUCWj3emCGpK9K24Jff2E11XrlJD3RMLNzFw2c90DFJoxb1PdWu0eb6Ko58h70gI1aez6ccIpK64KBcaE+dgvS9/zkgvnrz1hMlWaShP6FtvyT0swPG5n/Qz9sMDfluQSmSaY+Z6aYdRewthy3G2d97zSFsBl6PkHN9EfVvFnIjaV1Ni05BXwNvy+374aPFWgis/kM89zxlh0RnEYsTHtAa3EoPpB6zUxwYpWypyB8gjIGfsEnF/ScUea+vDEK9PollnJ4OLQRKTeBrx0OQzPfFyBPXz8xkNHYyUP6xdpU1JSMlAGTHoj59NaN7DgK01HXVX8tWCMqgBdeWgZUXwXkJkmjmoSCy58kIx3HEVnr8dAVB8eYqmqRRShcSL//h5lVam6HenCJAXoKDITczwsVvxA=
  gem: rubocop-cask
  on:
    tags: true
    repo: Homebrew/rubocop-cask
    branch: master
