language: ruby

sudo: false

cache: bundler

rvm:
  - 2.3.3
  - 2.3.6
  - 2.4.3
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true

before_script:
  - git config --local user.email "travis@travis.ci"
  - git config --local user.name "Travis CI"

script:
  - bundle exec rake coverage
  - bundle exec overcommit --sign
  - bundle exec overcommit --run

addons:
  code_climate:
    repo_token: e2ca7cf0efb5e3d667d5b0b9afab6f70351646eebce0dcfbd64dfd5f51da8e26
