language: ruby

sudo: false

cache: bundler

rvm:
  - 2.3.3
  - 2.3.6
  - 2.4.3
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true

before_script:
  - git config --local user.email "travis@travis.ci"
  - git config --local user.name "Travis CI"

script:
  - bundle exec rake coverage
  - bundle exec overcommit --sign
  - bundle exec overcommit --run

addons:
  code_climate:
    repo_token:
      secure: IeYsbcr/+95oCgVU4ob/v7MmmMaaarj3mdu6Tf06F+AoliHYO+c68EZtzB3T7QEPQQ61xj9Z6mgOYh9mO5RGOvJPTq4biaZaMpkhFYC9gj+NcpGNP0ZdrKPVWYGVfLQXceSB3v/2NSbgCs+gP8ld0bn7JsLsvCZpoLIeJB9HHVb9r/pUOAI+cpNHkq5M+q8H2w5rdV+eGLbNrvgs4fEo5Y8V405QrpUWfXntW/KULFuMYImDFkrl4bM5knmBg/LqMT2aGxoSHOrSAWhYSlT4vlJ6s34TDCO9aCk6HPwaQn95CizusvA5mSlhcCn+Pjz1OQRfniErlEcDSh2pfU9/A8j2YGvmnd8z2WgMisrqtpw8E0FiEJGKW2wDskvuni8ymwQ6rboGy4p5ho8VPlqu754Pkx4L9Af+DTNV0w6dZiM1TMMGIlOkpLNmJwQJ1Em1nYBUficGZafzgcD3oPfsblLelr63RnfDKuC8A/hIjiYYn7emXt+QMa8z4jBeCnrZ0oLA8jd/rGYWMNTLIbwTZzD/OWMPJX2n+BfLEUHMHwH0Eei/AI2nvAShzNXg5NEtkWwmzTzWBWPqPBoV9+XSPOLDsjVYOEIOzeD/2E3n9bcuyA/rpLdPmS5vgvgb837xclvfAU93Z1x/JQgcRU/jx8EyGbNmVFMvM2yBwc2Bzv0=
