language: ruby

sudo: false

cache: bundler

rvm:
  - 2.1.10
  - 2.2.8
  - 2.3.3
  - 2.3.5
  - 2.4.2
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-2
  fast_finish: true

before_install:
  - gem update --system --no-ri --no-rdoc
  - gem update --remote bundler

before_script:
  - git config --local user.email "travis@travis.ci"
  - git config --local user.name "Travis CI"

script:
  - bundle exec rake coverage
  - bundle exec overcommit --sign
  - bundle exec overcommit --run

addons:
  code_climate:
    repo_token: e2ca7cf0efb5e3d667d5b0b9afab6f70351646eebce0dcfbd64dfd5f51da8e26
